id: ID699AF9F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T14:27:25+00:00'
last_modified: '2022-06-08T13:06:48.933245+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC247
  title: 'དཔལ་ལྡན་དུས་ཀྱི་འཁོར་ལོ་ཇོ་ནང་པའི་བརྒྱུད་རིམ་བླ་མའི་རྣམ་ཐར། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    FE0A:
      image_group_id: I2PD18651
      title: ''
      total_pages: 468
      order: 1
      base_file: FE0A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
